# 5. Python NumPy

# Numerical Python (NumPy)
Numpy is one of the fundamental packages that you will be using a lot throughout this semester. It's mainly used for scientific computing. It provides convenient and efficient ways to manipulate data in arrays, as well as conduct vector operations. You can refer to its [Documentation page](https://numpy.org/doc/stable/) for more detailed information.

Before we can achieve anything remotely productive, we first need to import the Numpy package.

In [2]:
import numpy as np

## Creating Arrays
Numpy provides a number of different ways to initialize and populate arrays. The first method is by first creating a list and converting it to a Numpy array. You can click on the 'raw' button to see the actual list.

In [3]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

You can also just pass in a list directly.

In [4]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

To create a multidimensional array (a matrix), you can pass in a list of lists.

In [5]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7, 8, 9],
 [10, 11, 12]])

Use the `shape` method to find the dimensions of the array which will be output as (rows, columns)

In [6]:
# also applies to panda dataframes
m.shape

(2, 3)

The `arange` function returns evenly-spaced values within a given interval.

In [7]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

Numpy's `reshape` returns an array with the same data with a new shape.

In [8]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0, 2, 4, 6, 8],
 [10, 12, 14, 16, 18],
 [20, 22, 24, 26, 28]])

The `linspace` function returns evenly-spaced numbers over a specified interval.

In [9]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

The `resize` function changes the shape and size of array in-place. That is, it modifies the original array.

In [10]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
 [1.5, 2. , 2.5],
 [3. , 3.5, 4. ]])

Numpy `ones` returns a new array of given shape and type, filled with ones.

In [ ]:
np.ones((3, 2))

The `zeros` function returns a new array of given shape and type, filled with zeros. The first parameter can be an integer (1D array) or a tuple (a matrix). The second parameter is *optional*; it uses the `dtype` keyword that allows the user to indicate if they would like to specify an array or a matrix of integers or floats.

In [ ]:
np.zeros((2, 3))

### Try this out!
Try to create a Numpy 2D float matrix of size (3,6). Next, in a for loop, populate each row with identical arrays of 6 values that are evenly-spaced from 0 to 3.

In [ ]:
# Write your code here

The `eye` function returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [14]:
onezies = np.eye(3)
rand_arr = np.zeros((3,3)) + 3
rand_arr*onezies

array([[3., 0., 0.],
 [0., 3., 0.],
 [0., 0., 3.]])

Numpy `diag` extracts a diagonal or constructs a diagonal array.

In [ ]:
np.diag(y)

Create an array using repeating list (or see `np.tile`)

In [15]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

You can repeat elements of an array using `repeat`.

In [ ]:
np.repeat([1, 2, 3], 3)

## Combining Arrays
Sometimes, it might be useful to combine arrays that contain the same (or similar) information. Let's look at a couple of ways to combine arrays using Numpy.

First, we initialize a Numpy matrix of ones.

In [17]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
 [1, 1, 1]])

Use `vstack` to stack arrays in sequence vertically (row wise, or on top of each other).

In [18]:
np.vstack([p, 2*p])

array([[1, 1, 1],
 [1, 1, 1],
 [2, 2, 2],
 [2, 2, 2]])

Use `hstack` to stack arrays in sequence horizontally (column wise, or beside each other).

In [19]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
 [1, 1, 1, 2, 2, 2]])

## Operations
### Basic Operations
The basic operations in Numpy are your usual suspects- use `+`, `-`, `*`, `/` and `**` to perform element-wise addition, subtraction, multiplication, division and power.

In [20]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [21]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [22]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


### The dot product
The dot product (implemented using the `dot()` function) is a concise way of conducting element-wise multiplication and addition.  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [23]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [24]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


### Transposing arrays 
Let's look at transposing arrays. Transposing permutes the dimensions of the array. Let's take a look at how transposing affects our new array `z`.

In [25]:
z = np.array([y, y**2])
z

array([[ 4, 5, 6],
 [16, 25, 36]])

The shape of array `z` is `(2,3)` before transposing.

In [26]:
z.shape

(2, 3)

Use `.T` to get the transpose.

In [28]:
z.transpose()

array([[ 4, 16],
 [ 5, 25],
 [ 6, 36]])

The number of rows has swapped with the number of columns!

In [ ]:
z.T.shape

Use the Numpy `.dtype` method to see the data type of the elements in the array.

In [29]:
z.dtype

dtype('int64')

Use `.astype` to cast all elements in the array to a specific type.

In [30]:
z = z.astype('f')
z.dtype

dtype('float32')

## Math Functions
Numpy has many built-in math functions that can be performed on arrays. We will demonstrate them on a new array `a`.

In [31]:
a = np.array([-4, -2, 1, 3, 5])

In [ ]:
a.sum()

In [ ]:
a.max()

In [ ]:
a.min()

In [ ]:
a.mean()

In [ ]:
a.std()

`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [ ]:
a.argmax()

In [ ]:
a.argmin()

## Indexing / Slicing
In Numpy, we can use bracket notation to get the value at a specific index. Remember that indexing in Python starts at 0. We explore indexing with Numpy using a new array `s`.

In [33]:
s = np.power(np.arange(13),2)
s

array([ 0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144])

In [ ]:
s[0], s[4], s[-1]

Use `:` to indicate a range. `array[start:stop]`

Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [35]:
s[:]

array([ 0, 1, 4, 9, 16])

<br>
Use negatives to count from the back.

In [36]:
s[-4:]

array([ 81, 100, 121, 144])

A second `:` can be used to indicate step size where `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [37]:
s[-5::-2]

array([64, 36, 16, 4, 0])

Now, let's look at a multidimensional array.

In [48]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0, 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23],
 [24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35]])

We can still use bracket notation to slice, but this time, we add one more dimension to it where the first dimension is the row, and the second dimension is the column: `array[row, column]`

In [41]:
r[2, 2:]

array([14, 15, 16, 17])

Similarly, we can use `:` to select a range of rows and/or columns

In [42]:
r[3, 3:6]

array([21, 22, 23])

Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [43]:
r[:2, :-1]

array([[ 0, 1, 2, 3, 4],
 [ 6, 7, 8, 9, 10]])

This is a slice of the last row, and only every other element.

In [44]:
r[-1, ::2]

array([30, 32, 34])

We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [45]:
r[r > 30]

array([31, 32, 33, 34, 35])

Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [49]:
r[r > 30] = -1
r

array([[ 0, 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23],
 [24, 25, 26, 27, 28, 29],
 [30, -1, -1, -1, -1, -1]])

## Copying Data
Be careful with copying and modifying arrays in NumPy! Let's walk through some common errors using the `r` array.

`r2` is a slice of `r`

In [50]:
r2 = r[:3,:3]
r2

array([[ 0, 1, 2],
 [ 6, 7, 8],
 [12, 13, 14]])

Set this slice's values to zero (`[:]` selects the entire array)

In [51]:
# change each element in r2 to 0
# bad --> r2 = 0
r2[:] = 0
r2

array([[0, 0, 0],
 [0, 0, 0],
 [0, 0, 0]])

Note that `r` has also been changed!

In [52]:
r

array([[ 0, 0, 0, 3, 4, 5],
 [ 0, 0, 0, 9, 10, 11],
 [ 0, 0, 0, 15, 16, 17],
 [18, 19, 20, 21, 22, 23],
 [24, 25, 26, 27, 28, 29],
 [30, -1, -1, -1, -1, -1]])

To avoid this, use `r.copy` to create a copy that will not affect the original array

In [53]:
r_copy = r.copy()
r_copy

array([[ 0, 0, 0, 3, 4, 5],
 [ 0, 0, 0, 9, 10, 11],
 [ 0, 0, 0, 15, 16, 17],
 [18, 19, 20, 21, 22, 23],
 [24, 25, 26, 27, 28, 29],
 [30, -1, -1, -1, -1, -1]])

Now when `r_copy` is modified, `r` will not be changed.

In [54]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 -1 -1 -1 -1 -1]]


## Iterating Over Arrays
Let demonstrate how to iterate over Numpy arrays. We start by creating a new 4-by-3 array of random numbers 0 to 9.

In [55]:
test = np.random.randint(0, 10, (4,3))
test

array([[6, 8, 8],
 [9, 9, 1],
 [9, 6, 3],
 [5, 7, 0]])

Iterate by row:

In [ ]:
for row in test:
    print(row)

Iterate by index:

In [56]:
for i in range(len(test)):
    print(test[i])

[6 8 8]
[9 9 1]
[9 6 3]
[5 7 0]


Iterate by row and index:

In [ ]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

We can use `zip` to iterate over multiple iterables.

In [ ]:
test2 = test**2
test2

In [ ]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j   )

# Break 

**Dumbo Octopus Fact**: The dumbo octopus is officially the cutest deep-sea octopus. No, this is not actually a fact, but I dare you to fight me on this - Google 'Dumbo octopus' and you'll know why.

We'll shortly move on to **6. Pandas**, so take a breather before we learn another Python package!

# 6. Pandas

# Python Pandas
The Python Pandas library is a useful tool for data analysis and manipulation. You can load the library into your DataLore notebook by running the following line. It is also useful to have the Python NumPy library loaded when working with dataframes. Press 'Shift+Enter' to execute a cell, or click the top left play button.

When using Pandas, it's handy to also import the Numpy package, as both are typically used in tandem. Let's load the both of them to begin.

In [57]:
import pandas as pd
import numpy as np 
import csv

## Pandas: The Dataframe data structure
Panda dataframes consist of columns and rows, where each column contains a specific data type while the overall dataframe can contain a variety of different data types. The complete Pandas documentation can be found [here](https://pandas.pydata.org/docs/).

To begin, we initialize a Pandas dataframe using our good 'ol `mpg.csv` file:

In [111]:
# Pandas how to make a dataframe
df = pd.read_csv('mpg.csv',sep=",", index_col=0)
df

ValueError: ValueError: DataFrame constructor not properly called!

## Pandas: Accessing and changing dataframe values
In this course, you might be required to access information within a provided dataframe. There are several ways to select, extract, filter, add, change and delete data within a Pandas dataframe. Let's explore a few methods below:

You can select and access data by using square brackets `[]` or by using the `.iloc[]` method

In [68]:
# Selecting and extracting data
#df_onecol = df['cty']

#df_subset = df[['cty', 'hwy']]
#df_subset
df_iloc = df.iloc[2,1]
df_iloc

'audi'

You can filter a dataframe via the following methods:
1. Specifying a column and values within a column that meets certain criteria
2. Using the `.sort_values()` function
3. Using the `.groupby()` function

In [75]:
# filtering a dataframe 
# I want only cars with city mileage = 20mpg 
df_filtered = df[df['cty']=='20']
df_filtered

manufacturer 
 model 
 displ 
 year 
 cyl 
 trans 
 drv 
 cty 
 hwy 
 fl 
 class 
 
 
 
 
 2 
 3 
 audi 
 a4 
 2 
 2008 
 4 
 manual(m6) 
 f 
 20 
 31 
 p 
 compact 
 
 
 9 
 10 
 audi 
 a4 quattro 
 2 
 2008 
 4 
 manual(m6) 
 4 
 20 
 28 
 p 
 compact 
 
 
 117 
 118 
 hyundai 
 tiburon 
 2 
 2008 
 4 
 manual(m5) 
 f 
 20 
 28 
 r 
 subcompact 
 
 
 118 
 119 
 hyundai 
 tiburon 
 2 
 2008 
 4 
 auto(l4) 
 f 
 20 
 27 
 r 
 subcompact 
 
 
 161 
 162 
 subaru 
 forester awd 
 2.5 
 2008 
 4 
 manual(m5) 
 4 
 20 
 27 
 r 
 suv 
 
 
 163 
 164 
 subaru 
 forester awd 
 2.5 
 2008 
 4 
 auto(l4) 
 4 
 20 
 26 
 r 
 suv 
 
 
 169 
 170 
 subaru 
 impreza awd 
 2.5 
 2008 
 4 
 auto(s4) 
 4 
 20 
 25 
 p 
 compact 
 
 
 170 
 171 
 subaru 
 impreza awd 
 2.5 
 2008 
 4 
 auto(s4) 
 4 
 20 
 27 
 r 
 compact 
 
 
 172 
 173 
 subaru 
 impreza awd 
 2.5 
 2008 
 4 
 manual(m5) 
 4 
 20 
 27 
 r 
 compact 
 
 
 225 
 226 
 volkswagen 
 new beetle 
 2.5 
 2008 
 5 
 manual(m5) 
 f 
 20 
 28 
 r 
 subcompact 
 
 
 226 
 227 
 volkswagen 
 new beetle 
 2.5 
 2008 
 5 
 auto(s6) 
 f 
 20 
 29 
 r 
 subcompact

Sometimes when we want to filter numbers in our dataframe, we need to run the following code on the particular column we are trying to filter numerically because it doesn't come in a type we need. If we don't run the following line and just proceed to the code block after it, we will see an error where we are comparing incompatible types of `str` and `int`. 

In [78]:
df.cyl = pd.to_numeric(df.cyl, errors='coerce').fillna(0).astype(np.int64)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0                 234 non-null    object
 1   manufacturer  234 non-null    object
 2   model         234 non-null    object
 3   displ         234 non-null    object
 4   year          234 non-null    object
 5   cyl           234 non-null    int64 
 6   trans         234 non-null    object
 7   drv           234 non-null    object
 8   cty           234 non-null    object
 9   hwy           234 non-null    object
 10  fl            234 non-null    object
 11  class         234 non-null    object
dtypes: int64(1), object(11)
memory usage: 22.1+ KB


In [88]:
# Filtering data
df_morethan = df[df['cyl'] > 5]

df_sortby = df.sort_values('cyl',ascending=False)
df_grouped = df.groupby('cyl')
df_grouped

Here are a few other method and functions you can use to modify your dataframe:
1. Using `.drop()` to delete specific rows 
2. Adding a new column by specfying a new column name and associating it with an array with the same number of rows as your existing dataframe
3. Join or combine two dataframes using the `append()` or `concat()` methods

In [103]:
# Deleting data
df_droprow = df.drop([3])
df_droprow

manufacturer 
 model 
 displ 
 year 
 cyl 
 trans 
 drv 
 cty 
 hwy 
 fl 
 class 
 
 
 
 
 0 
 1 
 audi 
 a4 
 1.8 
 1999 
 4 
 auto(l5) 
 f 
 18 
 29 
 p 
 compact 
 
 
 1 
 2 
 audi 
 a4 
 1.8 
 1999 
 4 
 manual(m5) 
 f 
 21 
 29 
 p 
 compact 
 
 
 2 
 3 
 audi 
 a4 
 2 
 2008 
 4 
 manual(m6) 
 f 
 20 
 31 
 p 
 compact 
 
 
 4 
 5 
 audi 
 a4 
 2.8 
 1999 
 6 
 auto(l5) 
 f 
 16 
 26 
 p 
 compact 
 
 
 5 
 6 
 audi 
 a4 
 2.8 
 1999 
 6 
 manual(m5) 
 f 
 18 
 26 
 p 
 compact 
 
 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 
 
 229 
 230 
 volkswagen 
 passat 
 2 
 2008 
 4 
 auto(s6) 
 f 
 19 
 28 
 p 
 midsize 
 
 
 230 
 231 
 volkswagen 
 passat 
 2 
 2008 
 4 
 manual(m6) 
 f 
 21 
 29 
 p 
 midsize 
 
 
 231 
 232 
 volkswagen 
 passat 
 2.8 
 1999 
 6 
 auto(l5) 
 f 
 16 
 26 
 p 
 midsize 
 
 
 232 
 233 
 volkswagen 
 passat 
 2.8 
 1999 
 6 
 manual(m5) 
 f 
 18 
 26 
 p 
 midsize 
 
 
 233 
 234 
 volkswagen 
 passat 
 3.6 
 2008 
 6 
 auto(s6) 
 f 
 17 
 26 
 p 
 midsize 
 
 
 
 233 rows × 12 columns

In [105]:
# Adding a column
df['new_col'] = np.random.random(df.shape[0])
df
# Join or combine two dataframes
#df1.append(df2)
#df1.concat(df2)

manufacturer 
 model 
 displ 
 year 
 cyl 
 trans 
 drv 
 cty 
 hwy 
 fl 
 class 
 new_col 
 
 
 
 
 0 
 1 
 audi 
 a4 
 1.8 
 1999 
 4 
 auto(l5) 
 f 
 18 
 29 
 p 
 compact 
 0.211880 
 
 
 1 
 2 
 audi 
 a4 
 1.8 
 1999 
 4 
 manual(m5) 
 f 
 21 
 29 
 p 
 compact 
 0.138993 
 
 
 2 
 3 
 audi 
 a4 
 2 
 2008 
 4 
 manual(m6) 
 f 
 20 
 31 
 p 
 compact 
 0.526625 
 
 
 3 
 4 
 audi 
 a4 
 2 
 2008 
 4 
 auto(av) 
 f 
 21 
 30 
 p 
 compact 
 0.726954 
 
 
 4 
 5 
 audi 
 a4 
 2.8 
 1999 
 6 
 auto(l5) 
 f 
 16 
 26 
 p 
 compact 
 0.330956 
 
 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 
 
 229 
 230 
 volkswagen 
 passat 
 2 
 2008 
 4 
 auto(s6) 
 f 
 19 
 28 
 p 
 midsize 
 0.877610 
 
 
 230 
 231 
 volkswagen 
 passat 
 2 
 2008 
 4 
 manual(m6) 
 f 
 21 
 29 
 p 
 midsize 
 0.618822 
 
 
 231 
 232 
 volkswagen 
 passat 
 2.8 
 1999 
 6 
 auto(l5) 
 f 
 16 
 26 
 p 
 midsize 
 0.723893 
 
 
 232 
 233 
 volkswagen 
 passat 
 2.8 
 1999 
 6 
 manual(m5) 
 f 
 18 
 26 
 p 
 midsize 
 0.970181 
 
 
 233 
 234 
 volkswagen 
 passat 
 3.6 
 2008 
 6 
 auto(s6) 
 f 
 17 
 26 
 p 
 midsize 
 0.139162 
 
 
 
 234 rows × 13 columns

## Pandas: Performing statistical operations
Pandas by default performs array operations - so for example, if you add 1 to a series, you are adding one to each element. You can also perform column-wise statistical operations on the dataframe. Some examples are shown below:

In [23]:
# mean, median, std deviation, max, min, count

# Using DataFrame.mean() method to get column average
df2 = df["Fee"].mean()

# Using DataFrame.mean() to get entire column mean
df2 = df.mean()

# Using multiple columns mean using DataFrame.mean()
df2 = df[["Fee","Discount"]].mean()

# We can get the median and other critical statistical values through the describe function such as median, min, max, and quartiles
df.describe()

# To get the minimum/max for each column in the dataframe
df.min() 
df.max()

# Min/max of particular column 
df['column'].min() 
df['column'].max() 

In [106]:
df.describe()

cyl 
 new_col 
 
 
 
 
 count 
 234.000000 
 234.000000 
 
 
 mean 
 5.888889 
 0.504269 
 
 
 std 
 1.611534 
 0.267189 
 
 
 min 
 4.000000 
 0.000092 
 
 
 25% 
 4.000000 
 0.277157 
 
 
 50% 
 6.000000 
 0.494657 
 
 
 75% 
 8.000000 
 0.726189 
 
 
 max 
 8.000000 
 0.997821

There is also a super powerful function called `apply()`. We are not going to go into it too much here, but it allows you to perform operations on a dataframe

In [110]:
df.apply(np.mean, axis=1)

TypeError: TypeError: Could not convert 1audia41.819994auto(l5)f1829pcompact to numeric

# Break 

**Panda Fact**: Did you know that pandas developed the ability to roll head-over-heels down steep hills to quickly escape predators?

Rolling is not mandatory, but take a quick break before moving on to tab **7. More Pandas**!

# 7. More Pandas

# The Series Data Structure

Similar to an array, you can store a set of values in a series. Series can only be one dimensional and are usually the way you would store data that you would like to model in a time series. In the example below we first create an array of strings of the animal names, and then create a series object by passing the array name variable into `pd.Series()`

In [4]:
import pandas as pd
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

0 Tiger
1 Bear
2 Moose
dtype: object

Series can also contain numbers.

In [27]:
numbers = [1, 2, 3]
pd.Series(numbers)

0 1
1 2
2 3
dtype: int64

We can include different kinds of types in series, such as both strings and None's. None is a keyword we can use for a null value that we would like to include. This is not the same as 0. 

In [28]:
animals = ['Tiger', 'Bear', None]
pd.Series(animals)

0 Tiger
1 Bear
2 None
dtype: object

When inserting a None type into a numerics only array, it will appear as a NaN value when the series is printed. This is the numeric type representation of a None. 

In [29]:
numbers = [1, 2, None]
pd.Series(numbers)

0 1.0
1 2.0
2 NaN
dtype: float64

We can ask python if it considers the numpy NaN object to be the same as None - since the output is False, it does not. This is because you cannot compare the values of null values, be it asking if it is greater, less, or equal to another null value. 

In [3]:
import numpy as np
np.nan == None

False

As mentioned before, we test if two NumPy `nan` objects are equal and get fasle. 

In [31]:
np.nan == np.nan

False

If we want to check if a certain value is a null value, we need to use the `np.isnan` function. This returns true or false. 

In [32]:
np.isnan(np.nan)

True

Series can also work like a dictionary - this means you can store a key - value pair in a series. In this example we want to store the countries that have won a given sports tournament. We want to be able to associate a country to a sport so we choose to store it in a dictionary format. Note that for this data type we use curly braces `{}` instead of square ones `[]` as arrays commonly do. 

In [4]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery Bhutan
Golf Scotland
Sumo Japan
Taekwondo South Korea
dtype: object

To display our indexes, which is the sports that were competed in at the tournament, we can find the values through printing `objectname.index`. If we had a set of different tournaments stored in multiple tournamnets, we could look through each object to find the particular tournamnet that held the particular sport we were looking for by looking at the index values. 

In [5]:
s.index

Index(['Archery', 'Golf', 'Sumo', 'Taekwondo'], dtype='object')

We can also create a dictionary type series by putting all the values in one array, the index values in another, and passing both into the `pd.Series` function which concatenates them into the same formatted object as we have seen above with the sports tournament and countries.

In [6]:
s = pd.Series(['Tiger', 'Bear', 'Moose'], index=['India', 'America', 'Canada'])
s

India Tiger
America Bear
Canada Moose
dtype: object

If we try to combine the above methods shown of entering a dictionary of sports and countries into an object that we called `sports`, and then passing this into the `pd.Series` function, but we also specify `index=[]` we need to be careful about what we input as the index values. If our values given to the function in `index=[]` do not match up with what we provided in `sports`, our values in `index=[]` will override what the `sports` object contains.

In [7]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
s

Golf Scotland
Sumo Japan
Hockey NaN
dtype: object

# Querying a Series

In [5]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

Archery Bhutan
Golf Scotland
Sumo Japan
Taekwondo South Korea
dtype: object

We can access values in our `s` object by using the `iloc` function which treats the object like an array. This allows us to find data with just the numerical index value based on the ordering of the data, instead of the key we have provided for korea in terms of its sport. 

In [9]:
s.iloc[3]

'South Korea'

If we wanted to find the particular country that is associated with `Golf` in our dictionary, we can use the `loc` function to find it based on what we put into our dictionary as the key for the value of Scotland. 

In [10]:
s.loc['Golf']

'Scotland'

We can also access the value of `South Korea` through just calling the index of 3 in the object itself without using iloc. Calling `s[3]`  is the same as calling `s.iloc[3]`

In [11]:
s[3]

'South Korea'

And the same as if we were to use `loc`, we can use the key to also find the associated value.

In [12]:
s['Golf']

'Scotland'

Lets create a series of float values.

In [8]:
s = pd.Series([100.00, 120.00, 101.00, 3.00])
s

0 100.0
1 120.0
2 101.0
3 3.0
dtype: float64

We can calculate the sum of the values in our series by writing a simple for loop.

In [15]:
total = 0
for item in s:
    total+=item
print(total)

324.0


Something neat about the Numpy library is that it already has a built in function to sum up series for us, so we don't need to write a for loop every time we want to find the sum but instead can just call `np.sum()` on the series.

In [9]:
import numpy as np

total = np.sum(s)
print(total)

324.0


Let's create a series of 10,000 random integers between 0 and 1000.

In [7]:
#this creates a big series of random numbers
s = pd.Series(np.random.randint(0,1000,10000))
s.head()

0 640
1 560
2 51
3 982
4 242
dtype: int64

we can use `len()` function to find the length of our series.

In [48]:
len(s)

10000

A double percent is called a 'cell magic'. It allows you to execute commands that you can't execute in Python, and is quite handy. In this case we want to see how long it takes to run 

In [49]:
%%timeit -n 100
summary = 0
for item in s:
    summary+=item

1.92 ms ± 29.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [50]:
%%timeit -n 100
summary = np.sum(s)

90.9 µs ± 6.45 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


We can shorten a for loop and instead write the following to add 2 to each value in our series.

In [51]:
s+=2 #adds two to each item in s using broadcasting
s.head()

0 277
1 867
2 562
3 684
4 447
dtype: int64

Let's actually compare how long it takes to add 2 to a series of 10,000 values by using a for loop compared to using the shortened way we saw above. We can see that using the for loop is much slower than the shortened method of `s+=2`

In [8]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
for label, value in s.iteritems():
    s.loc[label]= value+2

582 ms ± 1.71 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [57]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
s+=2

363 µs ± 55.6 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Let's create another series where we have both numbers and strings as the key-value pairs.

In [8]:
s = pd.Series([1, 2, 3])
s.loc['Animal'] = 'Bears'
s

0 1
1 2
2 3
Animal Bears
dtype: object

We can create multiple series and store them in independent variables and then combine them using `objectname.append()`. This adds the series we pass int the `append()` function onto the object we are referencing, which would be `original_sports` in this case.

In [10]:
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)

In [12]:
original_sports

Archery Bhutan
Golf Scotland
Sumo Japan
Taekwondo South Korea
dtype: object

In [11]:
cricket_loving_countries

Cricket Australia
Cricket Barbados
Cricket Pakistan
Cricket England
dtype: object

We've seen the individual series above, and now we can see that after we appended them together, the `original_sports` series is first, and then we have our `cricket_loving_countries` series right after. 

In [11]:
all_countries

Archery Bhutan
Golf Scotland
Sumo Japan
Taekwondo South Korea
Cricket Australia
Cricket Barbados
Cricket Pakistan
Cricket England
dtype: object

If we look up the key `Cricket` we can see that all the values entered under `Cricket` are returned to us. 

In [12]:
all_countries.loc['Cricket']

Cricket Australia
Cricket Barbados
Cricket Pakistan
Cricket England
dtype: object

# The DataFrame Data Structure

A DataFrame is a data structure that organizes data into a 2-dimensional table of rows and columns, much like a spreadsheet. DataFrames are one of the most common data structures used in modern data analytics because they are a flexible and intuitive way of storing and working with data.

In [30]:
import pandas as pd
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()

Name 
 Item Purchased 
 Cost 
 
 
 
 
 Store 1 
 Chris 
 Dog Food 
 22.5 
 
 
 Store 1 
 Kevyn 
 Kitty Litter 
 2.5 
 
 
 Store 2 
 Vinod 
 Bird Seed 
 5.0

We can get information using `loc` by the index row name, which in this case is 'Store 2'. This returns all the information in each column, along with the respective column name, for the index we ask for.

In [63]:
df.loc['Store 2']

Name Vinod
Item Purchased Bird Seed
Cost 5.0
Name: Store 2, dtype: object

We can use the `type()` function to see what datatype we are working with.

In [64]:
type(df.loc['Store 2'])

pandas.core.series.Series

In [65]:
df.loc['Store 1']

Name 
 Item Purchased 
 Cost 
 
 
 
 
 Store 1 
 Chris 
 Dog Food 
 22.5 
 
 
 Store 1 
 Kevyn 
 Kitty Litter 
 2.5

Let's take a look at the values under the index of `Store 1` and the values entered under the `Cost` column.

In [15]:
df.loc['Store 1', 'Cost']

Store 1 22.5
Store 1 2.5
Name: Cost, dtype: float64

We can transpose our dataframe, meaning we can switch what are our index and what are our column names. We do this by adding`.T` to the end of the dataframe object. 

In [16]:
df.T #transpose

Store 1 
 Store 1 
 Store 2 
 
 
 
 
 Name 
 Chris 
 Kevyn 
 Vinod 
 
 
 Item Purchased 
 Dog Food 
 Kitty Litter 
 Bird Seed 
 
 
 Cost 
 22.5 
 2.5 
 5.0

Now let's look at the cost column - Even though we have transposed the dataframe we still get the same result as if we did not transpose it. Compare your output to the `df['Cost]` output.

In [18]:
df.T.loc['Cost']

Store 1 22.5
Store 1 2.5
Store 2 5.0
Name: Cost, dtype: object

In [19]:
df['Cost']

Store 1 22.5
Store 1 2.5
Store 2 5.0
Name: Cost, dtype: float64

A couple lines above we ran `df.loc['Store 1', 'Cost']`. Compare your output with the command below with the output of that line. 
We can see we get the same output so you can write your query for getting the desired information from a dataframe in multiple ways.

In [20]:
df.loc['Store 1']['Cost']

Store 1 22.5
Store 1 2.5
Name: Cost, dtype: float64

The `:` character is used to indicate that you want all data in a particuar row or column. Here, we use it to indicate that we want all rows of data, but only for columns `Name` and  `Cost`. 

In [21]:
df.loc[:,['Name', 'Cost']]

Name 
 Cost 
 
 
 
 
 Store 1 
 Chris 
 22.5 
 
 
 Store 1 
 Kevyn 
 2.5 
 
 
 Store 2 
 Vinod 
 5.0

If we would like to remove a particular index from our dataframe, we can us the `drop()` function to do so. Let's see how that works with the lines below.

In [22]:
df.drop('Store 1') #the index dropped is displayed - but doing this doesn't drop the rows in place

Name 
 Item Purchased 
 Cost 
 
 
 
 
 Store 2 
 Vinod 
 Bird Seed 
 5.0

In [31]:
df = df.drop('Store 1') #we re assign our dataframe to be the one that has indexes of 'Store 1' dropped 
df #lets see our new dataframe

Name 
 Item Purchased 
 Cost 
 
 
 
 
 Store 2 
 Vinod 
 Bird Seed 
 5.0

Another option for dropping a row instead of reassigning the dataframe like we did above, is using the `inplace` argument in the `drop()` function. Let's show how this is done below.

In [27]:
#Re create the original dataframe 
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])

#Now lets drop the indexes of Store 1

df.drop('Store 1', inplace=True)

We can see that our resulting dataframe is now one that only contains the index of `Store 2`. 

In [34]:
df

Name 
 Item Purchased 
 Cost 
 
 
 
 
 Store 2 
 Vinod 
 Bird Seed 
 5.0

If we know that we want to manipulate our data, such as dropping certain indexes or columns but keep our original dataframe untouched, we'll want to use the `copy()` function to do so. Below we crate a copy of our `df` object into `copy_df`, which we end up dropping the indeces that are `Store 1`.

In [35]:
#Re create the original dataframe 
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])

copy_df = df.copy()
copy_df = copy_df.drop('Store 1')
copy_df

Name 
 Item Purchased 
 Cost 
 
 
 
 
 Store 2 
 Vinod 
 Bird Seed 
 5.0

If we would like more information about a function we are trying to use, such as `drop`, we can get the respective library to show us the man function for it through the `?` character at the end of the function such as seen below. Here we have a walk through about relevant information for utilizing this function and usually an example is also given. You can find similar information online when looking up the function in the packages web page. 

In [36]:
copy_df.drop?

Signature:
copy_df.drop(
    labels=None,
    axis: 'Axis' = 0,
    index=None,
    columns=None,
    level: 'Level | None' = None,
    inplace: 'bool' = False,
    errors: 'str' = 'raise',
)
Docstring:
Drop specified labels from rows or columns.

Remove rows or columns by specifying label names and corresponding
axis, or by specifying directly index or column names. When using a
multi-index, labels on different levels can be removed by specifying
the level. See the `user guide <advanced.shown_levels>`
for more information about the now unused levels.

Parameters
----------
labels : single label or list-like
    Index or column labels to drop.
axis : {0 or 'index', 1 or 'columns'}, default 0
    Whether to drop labels from the index (0 or 'index') or
    columns (1 or 'columns').
index : single label or list-like
    Alternative to specifying axis (``labels, axis=0``
    is equivalent to ``index=labels``).
columns : single label or list-like
    Alternative to specifying axis (``labels

If we want to delete a column from our dataframe we use the keyword `del` to do so and then indicate the column we are wishing to delete. This changes the dataframe in place. 

In [37]:
del copy_df['Name']
copy_df

# Does not return a copy. Changes dataframe.

Item Purchased 
 Cost 
 
 
 
 
 Store 2 
 Bird Seed 
 5.0

If we would like to include a new column into our dataframe, but perhaps have not yet generated the data or are going to manipulate existing data in our dataframe to get that column's data, we can simply fill it with None types by doing the following. When we show our new dataframe the `Location` column now exists with no data in it. 

In [38]:
df['Location'] = None
df

Name 
 Item Purchased 
 Cost 
 Location 
 
 
 
 
 Store 1 
 Chris 
 Dog Food 
 22.5 
 None 
 
 
 Store 1 
 Kevyn 
 Kitty Litter 
 2.5 
 None 
 
 
 Store 2 
 Vinod 
 Bird Seed 
 5.0 
 None

In [ ]:
# Dataframe Indexing and Loading

We can isolate certain columns in our dataframe into a new dataframe while keeping our indexes

In [39]:
costs = df['Cost']
costs

Store 1 22.5
Store 1 2.5
Store 2 5.0
Name: Cost, dtype: float64

If we would like to add 2 to all values in the dataframe that consists of a single column, we can do so 

In [40]:
costs+=2
costs

Store 1 24.5
Store 1 4.5
Store 2 7.0
Name: Cost, dtype: float64

We can see here that since we created a pointer to the dataframe of just the `Cost` column, we actually edit the original dataframe's values. If we wanted to create the same dataframe as above but **not** edit the values within it, we would need to create a copy of the subset of the dataframe we would like to work with. 

In [41]:
df

Name 
 Item Purchased 
 Cost 
 Location 
 
 
 
 
 Store 1 
 Chris 
 Dog Food 
 24.5 
 None 
 
 
 Store 1 
 Kevyn 
 Kitty Litter 
 4.5 
 None 
 
 
 Store 2 
 Vinod 
 Bird Seed 
 7.0 
 None

In [42]:
!cat olympics.csv

cat: olympics.csv: No such file or directory


In [24]:
df = pd.read_csv('olympics.csv') #read the csv into our dataframe
df.head()

0 
 1 
 2 
 3 
 4 
 5 
 6 
 7 
 8 
 9 
 10 
 11 
 12 
 13 
 14 
 15 
 
 
 
 
 0 
 NaN 
 № Summer 
 01 ! 
 02 ! 
 03 ! 
 Total 
 № Winter 
 01 ! 
 02 ! 
 03 ! 
 Total 
 № Games 
 01 ! 
 02 ! 
 03 ! 
 Combined total 
 
 
 1 
 Afghanistan (AFG) 
 13 
 0 
 0 
 2 
 2 
 0 
 0 
 0 
 0 
 0 
 13 
 0 
 0 
 2 
 2 
 
 
 2 
 Algeria (ALG) 
 12 
 5 
 2 
 8 
 15 
 3 
 0 
 0 
 0 
 0 
 15 
 5 
 2 
 8 
 15 
 
 
 3 
 Argentina (ARG) 
 23 
 18 
 24 
 28 
 70 
 18 
 0 
 0 
 0 
 0 
 41 
 18 
 24 
 28 
 70 
 
 
 4 
 Armenia (ARM) 
 5 
 1 
 2 
 9 
 12 
 6 
 0 
 0 
 0 
 0 
 11 
 1 
 2 
 9 
 12

In [10]:
# we tell pandas to skip the first row, making the column titles in the correct place
df = pd.read_csv('olympics.csv', index_col = 0, skiprows=1) 
df.head() # lets us view the first 5 rows and all columns of the dataframe

№ Summer 
 01 ! 
 02 ! 
 03 ! 
 Total 
 № Winter 
 01 !.1 
 02 !.1 
 03 !.1 
 Total.1 
 № Games 
 01 !.2 
 02 !.2 
 03 !.2 
 Combined total 
 
 
 
 
 Afghanistan (AFG) 
 13 
 0 
 0 
 2 
 2 
 0 
 0 
 0 
 0 
 0 
 13 
 0 
 0 
 2 
 2 
 
 
 Algeria (ALG) 
 12 
 5 
 2 
 8 
 15 
 3 
 0 
 0 
 0 
 0 
 15 
 5 
 2 
 8 
 15 
 
 
 Argentina (ARG) 
 23 
 18 
 24 
 28 
 70 
 18 
 0 
 0 
 0 
 0 
 41 
 18 
 24 
 28 
 70 
 
 
 Armenia (ARM) 
 5 
 1 
 2 
 9 
 12 
 6 
 0 
 0 
 0 
 0 
 11 
 1 
 2 
 9 
 12 
 
 
 Australasia (ANZ) [ANZ] 
 2 
 3 
 4 
 5 
 12 
 0 
 0 
 0 
 0 
 0 
 2 
 3 
 4 
 5 
 12

In [11]:
# View the names of the columns in our dataframe
df.columns

Index(['№ Summer', '01 !', '02 !', '03 !', 'Total', '№ Winter', '01 !.1',
       '02 !.1', '03 !.1', 'Total.1', '№ Games', '01 !.2', '02 !.2', '03 !.2',
       'Combined total'],
      dtype='object')

We can format the way we show our dataframe to have different column names that are more descriptive to better display our data

In [12]:
for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold' + col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver' + col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze' + col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#' + col[1:]}, inplace=True) 

df.head()

# Summer 
 Gold 
 Silver 
 Bronze 
 Total 
 # Winter 
 Gold.1 
 Silver.1 
 Bronze.1 
 Total.1 
 # Games 
 Gold.2 
 Silver.2 
 Bronze.2 
 Combined total 
 
 
 
 
 Afghanistan (AFG) 
 13 
 0 
 0 
 2 
 2 
 0 
 0 
 0 
 0 
 0 
 13 
 0 
 0 
 2 
 2 
 
 
 Algeria (ALG) 
 12 
 5 
 2 
 8 
 15 
 3 
 0 
 0 
 0 
 0 
 15 
 5 
 2 
 8 
 15 
 
 
 Argentina (ARG) 
 23 
 18 
 24 
 28 
 70 
 18 
 0 
 0 
 0 
 0 
 41 
 18 
 24 
 28 
 70 
 
 
 Armenia (ARM) 
 5 
 1 
 2 
 9 
 12 
 6 
 0 
 0 
 0 
 0 
 11 
 1 
 2 
 9 
 12 
 
 
 Australasia (ANZ) [ANZ] 
 2 
 3 
 4 
 5 
 12 
 0 
 0 
 0 
 0 
 0 
 2 
 3 
 4 
 5 
 12

# Querying a DataFrame

We can query our dataframes to tell us more about the data we are dealing with. Below we return true or false values for each row in the Gold column on whether or not the country has won a gold medal or not.

In [13]:
df['Gold'] > 0

Afghanistan (AFG) False
Algeria (ALG) True
Argentina (ARG) True
Armenia (ARM) True
Australasia (ANZ) [ANZ] True
 ... 
Independent Olympic Participants (IOP) [IOP] False
Zambia (ZAM) [ZAM] False
Zimbabwe (ZIM) [ZIM] True
Mixed team (ZZX) [ZZX] True
Totals True
Name: Gold, Length: 147, dtype: bool

In [15]:
only_gold = df.where(df['Gold'] > 0)
only_gold.head() # We only display countries that have won gold at least once 

# Summer 
 Gold 
 Silver 
 Bronze 
 Total 
 # Winter 
 Gold.1 
 Silver.1 
 Bronze.1 
 Total.1 
 # Games 
 Gold.2 
 Silver.2 
 Bronze.2 
 Combined total 
 
 
 
 
 Afghanistan (AFG) 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 Algeria (ALG) 
 12.0 
 5.0 
 2.0 
 8.0 
 15.0 
 3.0 
 0.0 
 0.0 
 0.0 
 0.0 
 15.0 
 5.0 
 2.0 
 8.0 
 15.0 
 
 
 Argentina (ARG) 
 23.0 
 18.0 
 24.0 
 28.0 
 70.0 
 18.0 
 0.0 
 0.0 
 0.0 
 0.0 
 41.0 
 18.0 
 24.0 
 28.0 
 70.0 
 
 
 Armenia (ARM) 
 5.0 
 1.0 
 2.0 
 9.0 
 12.0 
 6.0 
 0.0 
 0.0 
 0.0 
 0.0 
 11.0 
 1.0 
 2.0 
 9.0 
 12.0 
 
 
 Australasia (ANZ) [ANZ] 
 2.0 
 3.0 
 4.0 
 5.0 
 12.0 
 0.0 
 0.0 
 0.0 
 0.0 
 0.0 
 2.0 
 3.0 
 4.0 
 5.0 
 12.0

In [18]:
only_gold['Gold'].count() # How many countries have won gold

100

In [17]:
df['Gold'].count() #How many countries total 

147

In [19]:
only_gold = only_gold.dropna()
only_gold.head()

# Summer 
 Gold 
 Silver 
 Bronze 
 Total 
 # Winter 
 Gold.1 
 Silver.1 
 Bronze.1 
 Total.1 
 # Games 
 Gold.2 
 Silver.2 
 Bronze.2 
 Combined total 
 
 
 
 
 Algeria (ALG) 
 12.0 
 5.0 
 2.0 
 8.0 
 15.0 
 3.0 
 0.0 
 0.0 
 0.0 
 0.0 
 15.0 
 5.0 
 2.0 
 8.0 
 15.0 
 
 
 Argentina (ARG) 
 23.0 
 18.0 
 24.0 
 28.0 
 70.0 
 18.0 
 0.0 
 0.0 
 0.0 
 0.0 
 41.0 
 18.0 
 24.0 
 28.0 
 70.0 
 
 
 Armenia (ARM) 
 5.0 
 1.0 
 2.0 
 9.0 
 12.0 
 6.0 
 0.0 
 0.0 
 0.0 
 0.0 
 11.0 
 1.0 
 2.0 
 9.0 
 12.0 
 
 
 Australasia (ANZ) [ANZ] 
 2.0 
 3.0 
 4.0 
 5.0 
 12.0 
 0.0 
 0.0 
 0.0 
 0.0 
 0.0 
 2.0 
 3.0 
 4.0 
 5.0 
 12.0 
 
 
 Australia (AUS) [AUS] [Z] 
 25.0 
 139.0 
 152.0 
 177.0 
 468.0 
 18.0 
 5.0 
 3.0 
 4.0 
 12.0 
 43.0 
 144.0 
 155.0 
 181.0 
 480.0

In [20]:
only_gold = df[df['Gold'] > 0]
only_gold.head()

# Summer 
 Gold 
 Silver 
 Bronze 
 Total 
 # Winter 
 Gold.1 
 Silver.1 
 Bronze.1 
 Total.1 
 # Games 
 Gold.2 
 Silver.2 
 Bronze.2 
 Combined total 
 
 
 
 
 Algeria (ALG) 
 12 
 5 
 2 
 8 
 15 
 3 
 0 
 0 
 0 
 0 
 15 
 5 
 2 
 8 
 15 
 
 
 Argentina (ARG) 
 23 
 18 
 24 
 28 
 70 
 18 
 0 
 0 
 0 
 0 
 41 
 18 
 24 
 28 
 70 
 
 
 Armenia (ARM) 
 5 
 1 
 2 
 9 
 12 
 6 
 0 
 0 
 0 
 0 
 11 
 1 
 2 
 9 
 12 
 
 
 Australasia (ANZ) [ANZ] 
 2 
 3 
 4 
 5 
 12 
 0 
 0 
 0 
 0 
 0 
 2 
 3 
 4 
 5 
 12 
 
 
 Australia (AUS) [AUS] [Z] 
 25 
 139 
 152 
 177 
 468 
 18 
 5 
 3 
 4 
 12 
 43 
 144 
 155 
 181 
 480

In [21]:
len(df[(df['Gold'] > 0) | (df['Gold.1'] > 0)])

101

In [22]:
df[(df['Gold.1'] > 0) & (df['Gold'] == 0)]

# Summer 
 Gold 
 Silver 
 Bronze 
 Total 
 # Winter 
 Gold.1 
 Silver.1 
 Bronze.1 
 Total.1 
 # Games 
 Gold.2 
 Silver.2 
 Bronze.2 
 Combined total 
 
 
 
 
 Liechtenstein (LIE) 
 16 
 0 
 0 
 0 
 0 
 18 
 2 
 2 
 5 
 9 
 34 
 2 
 2 
 5 
 9

# Indexing Dataframes

In [ ]:
df.head()

In [ ]:
df['country'] = df.index
df = df.set_index('Gold')
df.head()

In [ ]:
df = df.reset_index()
df.head()

In [ ]:
df = pd.read_csv('census.csv')
df.head()

In [ ]:
df['SUMLEV'].unique()

In [ ]:
df=df[df['SUMLEV'] == 50]
df.head()

In [ ]:
columns_to_keep = ['STNAME',
                   'CTYNAME',
                   'BIRTHS2010',
                   'BIRTHS2011',
                   'BIRTHS2012',
                   'BIRTHS2013',
                   'BIRTHS2014',
                   'BIRTHS2015',
                   'POPESTIMATE2010',
                   'POPESTIMATE2011',
                   'POPESTIMATE2012',
                   'POPESTIMATE2013',
                   'POPESTIMATE2014',
                   'POPESTIMATE2015']
df = df[columns_to_keep]
df.head()

In [ ]:
df = df.set_index(['STNAME', 'CTYNAME'])
df.head()

In [ ]:
df.loc['Michigan', 'Washtenaw County']

In [ ]:
df.loc[ [('Michigan', 'Washtenaw County'),
         ('Michigan', 'Wayne County')] ]

# Missing values

In [ ]:
df = pd.read_csv('log.csv')
df

In [ ]:
df.fillna?

In [ ]:
df = df.set_index('time')
df = df.sort_index()
df

In [ ]:
df = df.reset_index()
df = df.set_index(['time', 'user'])
df

In [ ]:
df = df.fillna(method='ffill')
df.head()

# Merging Dataframes

In [ ]:
import pandas as pd

df = pd.DataFrame([{'Name': 'Chris', 'Item Purchased': 'Sponge', 'Cost': 22.50},
                   {'Name': 'Kevyn', 'Item Purchased': 'Kitty Litter', 'Cost': 2.50},
                   {'Name': 'Filip', 'Item Purchased': 'Spoon', 'Cost': 5.00}],
                  index=['Store 1', 'Store 1', 'Store 2'])
df

In [ ]:
df['Date'] = ['December 1', 'January 1', 'mid-May']
df

In [ ]:
df['Delivered'] = True
df

In [ ]:
df['Feedback'] = ['Positive', None, 'Negative']
df

In [ ]:
adf = df.reset_index()
adf['Date'] = pd.Series({0: 'December 1', 2: 'mid-May'})
adf

In [ ]:
staff_df = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR'},
                         {'Name': 'Sally', 'Role': 'Course liasion'},
                         {'Name': 'James', 'Role': 'Grader'}])
staff_df = staff_df.set_index('Name')
student_df = pd.DataFrame([{'Name': 'James', 'School': 'Business'},
                           {'Name': 'Mike', 'School': 'Law'},
                           {'Name': 'Sally', 'School': 'Engineering'}])
student_df = student_df.set_index('Name')
print(staff_df.head())
print()
print(student_df.head())

In [ ]:
pd.merge(staff_df, student_df, how='outer', left_index=True, right_index=True)

In [ ]:
pd.merge(staff_df, student_df, how='inner', left_index=True, right_index=True)

In [ ]:
pd.merge(staff_df, student_df, how='left', left_index=True, right_index=True)

In [ ]:
pd.merge(staff_df, student_df, how='right', left_index=True, right_index=True)

In [ ]:
staff_df = staff_df.reset_index()
student_df = student_df.reset_index()
pd.merge(staff_df, student_df, how='left', left_on='Name', right_on='Name')

In [ ]:
staff_df = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR', 'Location': 'State Street'},
                         {'Name': 'Sally', 'Role': 'Course liasion', 'Location': 'Washington Avenue'},
                         {'Name': 'James', 'Role': 'Grader', 'Location': 'Washington Avenue'}])
student_df = pd.DataFrame([{'Name': 'James', 'School': 'Business', 'Location': '1024 Billiard Avenue'},
                           {'Name': 'Mike', 'School': 'Law', 'Location': 'Fraternity House #22'},
                           {'Name': 'Sally', 'School': 'Engineering', 'Location': '512 Wilson Crescent'}])
pd.merge(staff_df, student_df, how='left', left_on='Name', right_on='Name')

In [ ]:
staff_df = pd.DataFrame([{'First Name': 'Kelly', 'Last Name': 'Desjardins', 'Role': 'Director of HR'},
                         {'First Name': 'Sally', 'Last Name': 'Brooks', 'Role': 'Course liasion'},
                         {'First Name': 'James', 'Last Name': 'Wilde', 'Role': 'Grader'}])
student_df = pd.DataFrame([{'First Name': 'James', 'Last Name': 'Hammond', 'School': 'Business'},
                           {'First Name': 'Mike', 'Last Name': 'Smith', 'School': 'Law'},
                           {'First Name': 'Sally', 'Last Name': 'Brooks', 'School': 'Engineering'}])
staff_df
student_df
pd.merge(staff_df, student_df, how='inner', left_on=['First Name','Last Name'], right_on=['First Name','Last Name'])

# 8. Python Matplotlib

# Plotting Data in Matplotlib
Matplotlib is a Python library that enables the creation of both static and interactive visualizations. Its full documentation and helpful tutorials can be found [here](https://matplotlib.org/stable/users/index.html). It can be imported into your notebook using the following line:

In [112]:
import matplotlib.pyplot as plt

## Matplotlib: Making a figure
The most reliable way to create a plot using Matplotlib is via the `subplots()` function. The demonstration below shows you how to generate a simple scatter plot, label its axes, as well as create a plot title and legend.

In [115]:
# dataset-1
x1 = [89, 43, 36, 36, 95, 10,
      66, 34, 38, 20]
 
y1 = [21, 46, 3, 35, 67, 95,
      53, 72, 58, 10]
 
# dataset2
x2 = [26, 29, 48, 64, 6, 5,
      36, 66, 72, 40]
 
y2 = [26, 34, 90, 33, 38,
      20, 56, 2, 47, 15]

# Generate our points for the first set of data
plt.scatter(x1, y1, c ="pink",
            linewidths = 2,
            marker ="s",
            edgecolor ="green",
            s = 50, label="First dataset")

# Generate points for our second set of data
plt.scatter(x2, y2, c ="yellow",
            linewidths = 2,
            marker ="^",
            edgecolor ="red",
            s = 200, label='Second dataset')

# Add our X and Y Labels
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.legend()
plt.show() # Display the graph

## Matplotlib: Line plot
A simple line plot can be generated using the `plot()` function:

In [119]:
x = np.linspace(-1, 1, 50)
y1 = 2*x + 1
y2 = np.tan(x) + 1

# One data source where the index of the array is our x axis
plt.plot(x,y2)

In [39]:
# Where we are plotting two sets of values against each other 
plt.plot(x,y1)

# note the change of x axis values between this graph and above

In [121]:

plt.figure(num = 3, figsize=(8, 5)) #You can change how large the graph size displayed is with figsize 
plt.plot(x, y2, label="Blue line")
plt.plot(x, y1,  # We want to add a dashed red line here to represent the x,y1 relationship 
         color='red',   # color
         linewidth=1.0,  # line width
         linestyle='--', # what type of line
         label='Red line')

plt.title('Example plot')
plt.xlabel('decision variables')
plt.ylabel('Outcoms')

plt.legend()
plt.show()

## Matplotlib: Bar charts and histograms
In Matplotlib, a bar chart can be created simply by using the `bar()` function. A similar-looking figure, a histogram, can be generated using the `hist()` function. 

In [123]:
freq = [23, 45, 56, 78, 213]
plt.bar([1,2,3,4,5], freq)

plt.xlabel('Bins')
plt.ylabel('Frequency')
plt.show()

We can also make a stacked bar chart to show how two components of a total create a whole

In [128]:
data1 = [23,85, 72, 43, 52]
data2 = [42, 35, 21, 16, 9]

# plot a histogram
plt.bar(range(len(data1)), data1)

# plot more data at the bottom of the first 
plt.bar(range(len(data2)), data2, bottom=data1, color='green')
plt.show()

Let's make a hisogram now, which although looks similar is a different kind of chart

In [135]:
x = [21,22,23,4,5,6,77,8,9,10,31,32,33,34,35,36,37,18,49,50,100]
#x = np.random.randint(100)
num_bins = 5
n, bins, patches = plt.hist(x, num_bins, facecolor='blue', alpha=0.5)
plt.show()

## Matplotlib: Adding color gradients and color bars
The application of color gradients is useful to demonstrate three different information types on a two-dimensional plot. There are two important functions to note if you are considering the use of a color gradient:
1. `plt.colormaps(cmap_name)` Gets the name of the colormap you are using for your data
2. `plt.colorbar()` Adds a colorbar to your plot

In [136]:
# Matplotlib color gradient example
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(30)
y = x**3
t = x

plt.scatter(x, y, c=t)
plt.colorbar()
plt.show()

We need to create a new color map that we are going to use for our next plot 

In [6]:
def two_color_cmap(color1, color2, transition_value, transition_width, plot_min, plot_max):
    #build the colors sequence
    colors=[color1, color1, color2, color2]
    #scale the transition value into a 0-1 value in our plotted range
    transition = (transition_value - plot_min)/(plot_max - plot_min)
    #scale the transition width
    trans_width_scaled = transition_width / (plot_max - plot_min)
    #build the nodes list
    nodes=[0.0, transition - (trans_width_scaled/2), transition + (trans_width_scaled/2), 1.0]
    new_cmap = LinearSegmentedColormap.from_list("mycmap", list(zip(nodes, colors)))
    return(new_cmap)


In [8]:
import numpy as np
from matplotlib.colors import LinearSegmentedColormap

df = pd.DataFrame(data={'Month': [1, 2, 3, 4, 5, 6], 
                        'Patients': [22, 53, 42, 18, 31, 28]})

fig, ax = plt.subplots()
ax.bar(df.Month, df.Patients, color='#074d5e', edgecolor='black', zorder=3)
ax.set_ylabel('Patients')
ax.set_xlabel('Month')
ax.grid(which='major', axis='y', linestyle='--', color='black', zorder=0)

plotlim = plt.xlim() + plt.ylim()  
my_cmap= two_color_cmap("white", "#ff2626",35,4,plt.ylim()[0],plt.ylim()[1])
#set up the gradient
grad = np.atleast_2d(np.linspace(1,0,256)).T
ax.imshow(grad, cmap = my_cmap, aspect='auto', extent=plotlim)

plt.show()

## Matplotlib: 3-dimensional data
Creating a 3D plot using Matplotlib can require the use of two new functions:
1. `plt.figure()` Initializes a blank figure object
2. `plt.add_subplot(nrows, ncols, index, projection='3d')` Creates a 3D subplot object. If only one 3D plot is being generated, the values of `nrows`, `ncols`, and `index` should be set to 1.

A demonstration of generating a 3D plot is shown below:

In [140]:
from mpl_toolkits import mplot3d

ax = plt.axes(projection='3d')

# Data for a three-dimensional line
zline = np.linspace(0, 15, 1000)
xline = np.sin(zline)
yline = np.cos(zline)
ax.plot3D(xline, yline, zline, 'gray')

# Data for three-dimensional scattered points
zdata = 15 * np.random.random(100)
xdata = np.sin(zdata) + 0.1 * np.random.randn(100)
ydata = np.cos(zdata) + 0.1 * np.random.randn(100)
ax.scatter3D(xdata, ydata, zdata, c=zdata, cmap='RdBu');

plt.show()
#ax = plt.axes(projection='3d')
#ax.scatter(x, y, z, c=z, cmap='viridis', linewidth=0.5);

<function matplotlib.pyplot.show(close=None, block=None)>

# Try this out!
So far, you've learned how to run code in DataLore, basics of Python code, the Python Pandas and Matplotlib libraries. Attempt the exercise below to try out what you just learned!

Play around with some of the data we've seen already and either generate sample data yourself to graph various relationships in one graph with different colors, points, and styles. Try to combine graphs and see which can be overlayed on one another and which can't. The better you can visualize different relationships between data the better you can convey ideas quickly and coherently during your presentation of your findings!